name: "nodenoggin"

services:
  nodenoggin-web-app-service:
    image: nodenoggin.azurecr.io/nodenoggin-web-app:latest
    build:
      context: .
      dockerfile: products/app/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
        - VITE_SYNC_SERVER_ENDPOINT=${VITE_SYNC_SERVER_ENDPOINT:-wss://websockets.nodenogg.in/sync}
    container_name: web-app-${NODE_ENV:-development}
    ports:
      - "${WEB_PORT:-8080}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - nodenoggin-yjs-sync-server-service

  nodenoggin-yjs-sync-server-service:
    image: nodenoggin.azurecr.io/nodenoggin-yjs-sync-server:latest
    build:
      context: .
      dockerfile: products/yjs-sync-server/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    container_name: nodenoggin-yjs-sync-server-${NODE_ENV:-development}
    ports:
      - "${SERVER_PORT:-8787}:8787"
    expose: ["8787"]
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS:-https://www.nodenogg.in}
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(8787).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nodenoggin-docs-service:
    image: nodenoggin.azurecr.io/nodenoggin-docs:latest
    build:
      context: .
      dockerfile: docs/Dockerfile
    container_name: docs-${NODE_ENV:-development}
    ports:
      - "${DOCS_PORT:-8081}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

volumes:
  pnpm-store:
