name: "nodenoggin"
services:
  nodenoggin-web-app-service:
    build:
      context: .
      dockerfile: products/app/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
        - VITE_SYNC_SERVER_ENDPOINT=${VITE_SYNC_SERVER_ENDPOINT:-ws://localhost:8787/sync}
    container_name: web-app-${NODE_ENV:-development}
    ports:
      - "${WEB_PORT:-8080}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - nodenoggin-yjs-sync-server-service
  nodenoggin-yjs-sync-server-service:
    build:
      context: .
      dockerfile: products/yjs-sync-server/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    container_name: nodenoggin-yjs-sync-server-${NODE_ENV:-development}
    ports:
      - "${SERVER_PORT:-8787}:8787"
    expose: ["8787"]
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS:-http://localhost:8080}
    healthcheck:
      test: ["CMD", "node", "-e", "require('net').connect(8787).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pnpm-store:
