name: Deploy App to Azure from main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ">=20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Clean installation
        run: |
          rm -rf node_modules
          rm -rf packages/*/node_modules
          rm -f pnpm-lock.yaml
          pnpm store prune

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Update dependencies
        run: pnpm update

      - name: Install libraries
        run: pnpm build:lib

      - name: Debug Symbolic Links
        run: find . -type l

      - name: Handle Symbolic Links
        run: |
          find . -type l -exec sh -c 'cp --remove-destination "$(readlink -f "{}")" "{}"' \;

      - name: Run tests
        run: pnpm test

      - name: Change permission of the build script
        run: chmod +x ./build.sh

      - name: Execute custom build script
        run: ./build.sh

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_HILL_0F4662303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "products/app"
          api_location: ""
          output_location: "./dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_HILL_0F4662303 }}
          action: "close"
