name: Build Docs

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20.15.1"

      - name: Install dependencies
        run: |
          cd docs
          npm ci
          npm install @astrojs/check typescript @astrojs/starlight starlight-typedoc
          cd ..

      - name: Check installed packages and versions
        run: |
          cd docs
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Installed packages:"
          npm list --depth=0
          echo "Package.json contents:"
          cat package.json
          cd ..

      - name: Check Astro configuration
        run: |
          cd docs
          cat astro.config.mjs
          cd ..

      - name: Build
        run: |
          cd docs
          npm run build
          cd ..

      - name: Debug build output
        run: |
          echo "Contents of docs directory:"
          ls -la docs
          echo "Contents of docs/dist directory (if it exists):"
          ls -la docs/dist || echo "docs/dist does not exist"

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -f docs/dist
          git status
          git commit -m "fix: update documentation" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

      - name: Debug repository contents
        run: |
          echo "Contents of repository root:"
          ls -la
          echo "Contents of docs directory:"
          ls -la docs
          echo "Contents of docs/dist directory:"
          ls -la docs/dist

      - name: Copy built files
        run: |
          if [ -d "docs/dist" ]; then
            echo "Build output found in docs/dist"
          else
            echo "Error: Could not find built files in docs/dist. Check your build process."
            exit 1
          fi
          echo "Contents of docs/dist after build:"
          ls -la docs/dist

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -f docs/dist
          git status
          git commit -m "fix: update documentation" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

      - name: Debug repository contents
        run: |
          echo "Contents of repository root:"
          ls -la
          echo "Contents of docs directory:"
          ls -la docs
          echo "Contents of docs/dist directory:"
          ls -la docs/dist

  deploy:
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy to azure / docs.nodenogg.in
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_TREE_08C8E3A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "docs/dist" # Updated app source code path
