name: Build and Deploy Astro Site to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Build Astro site
        working-directory: ./docs
        run: npm run build

      - name: List build output
        run: ls -R docs/dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "docs/dist" # Changed to point directly to the build output
          output_location: "" # Changed to empty as we're pointing directly to the build output
          skip_app_build: true # Skip additional build steps
