name: Build Docs

on:
  push:
    branches:
      - main # Adjust branch name as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move into docs folder
        run: cd docs

      - name: Install dependencies
        run: npm install
        working-directory: docs # This ensures npm install runs in the 'docs' folder

      - name: Build
        run: npm run build
        working-directory: docs # This ensures npm run build runs in the 'docs' folder
