name: Build Docs

on:
  push:
    branches:
      - docbuilder # Adjust branch name as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ">=18.14.1"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install libraries
        run: pnpm build:lib

      - name: Move into docs folder
        run: cd docs

      - name: Install dependencies
        run: npm install
        working-directory: docs # This ensures npm install runs in the 'docs' folder

      - name: Build
        run: npm run build
        working-directory: docs # This ensures npm run build runs in the 'docs' folder

      - name: Create dist folder
        run: mkdir dist
        working-directory: docs # This ensures mkdir runs in the 'docs' folder

      - name: Move build files to dist folder
        run: mv * dist
        working-directory: docs # This ensures mv runs in the 'docs' folder

      - name: List contents of dist folder
        run: ls -l dist
        working-directory: docs
