name: Build and Deploy Astro Site to Azure

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your preferred Node.js version

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Build Astro site
        working-directory: ./docs
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "docs"
          output_location: "dist"
          skip_app_build: true
