name: Build Docs

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ">=18.14.1"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install libraries
        run: pnpm build:lib

      - name: Move into docs folder
        run: cd docs

      - name: Debug - Check package.json
        run: |
          cd docs 
          cat package.json 
          cd ..

      - name: Install dependencies in docs folder
        run: |
          cd docs
          npm install --verbose
          cd ..

      - name: Debug - List contents of docs directory
        run: ls -l

      - name: Build
        run: npm run build

      - name: Move back to the root directory
        run: cd ..

      - name: Debug build output
        run: |
          echo "Contents of docs directory:"
          ls -la docs
          echo "Contents of build output directory:"
          ls -la docs/build || ls -la docs/out || ls -la docs/public || echo "Could not find build output directory"

      - name: Copy built files
        run: |
          mkdir -p docs/dist
          if [ -d "docs/build" ]; then
            cp -R docs/build/* docs/dist/
          elif [ -d "docs/out" ]; then
            cp -R docs/out/* docs/dist/
          elif [ -d "docs/public" ]; then
            cp -R docs/public/* docs/dist/
          else
            echo "Error: Could not find built files. Check your build process."
            exit 1
          fi
          echo "Contents of docs/dist after copy:"
          ls -la docs/dist

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -f docs/dist
          git status
          git commit -m "fix: update documentation" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

  deploy:
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy to azure / docs.nodenogg.in
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_TREE_08C8E3A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "docs/dist" # Updated app source code path
