name: Build Docs

on:
  push:
    branches:
      - docbuilder # Adjust branch name as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ">=18.14.1"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install libraries
        run: pnpm build:lib

      - name: Move into docs folder
        run: cd docs

      - name: Install dependencies
        run: npm install
        working-directory: docs # This ensures npm install runs in the 'docs' folder

      - name: Build
        run: npm run build
        working-directory: docs

      - name: Create destination directory
        run: mkdir -p $GITHUB_WORKSPACE/../${GITHUB_REPOSITORY}/docs/dist

      - name: Copy files to repo
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cp -r docs/dist/* ../${GITHUB_REPOSITORY}/docs/dist/
          git add .
          git commit -m "Update dist files"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
